# script to calculate fraction of responders and non-responders (with respect to entire cohort) in subsets generated by top biomarkers

library(ggplot2)
library(dplyr)
source('plot_frac_resp_nonresp.R')

metric <- c("response", "ris")
datasets <- c("train", "test") #thein: test/validate
datasets2 <- c("train", "validate") #thein: test/validate

datasets_name <- c("Training", "Validation")
metric_names <- c("Response probability", "RIS")
resp_status = c("R", "NR")

for(i in 1:length(metric)){
  
  final_data <- NULL
  
  for(k in 1:length(datasets)){ # train or test

    for(j in 1:4){
      
      if(j==1){ # single biomarker
        read_data <- read.csv(paste0('single_', metric[i], '_', datasets[k], '.csv'))
      }else{
        read_data <- read.csv(paste0('all', j, '_', metric[i], '_', datasets2[k], '.csv'))
      }

      frac_resp_nonresp = c(read_data$fraction_responders[1], read_data$fraction_nonresponders[1])
        
        for(rs in 1:2){
          
          if(metric[i] == "response"){
            final_data = rbind(final_data, c(j, "Response probability", read_data$response_probability[1], datasets_name[k],
                                             frac_resp_nonresp[rs], resp_status[rs]))
            
          }else{
            final_data = rbind(final_data, c(j, "RIS", read_data$ris[1], datasets_name[k],
                                             frac_resp_nonresp[rs], resp_status[rs]))
            
          }
          
        }
      
    }
    
  }
  
  final_data < data.frame(final_data)
  
  final_data_train = final_data[which((final_data[,4]=="Training")),]
  final_data_test = final_data[which((final_data[,4]=="Validation")),]
  
  colors <- c("#DB72FB", "#00C19F","grey","darkolivegreen1")

  plot_frac_resp_nonresp(final_data_train, colors, metric[i], "train")
  plot_frac_resp_nonresp(final_data_test, colors, metric[i], "test")
  
}
